### ISSUE TITLE
Locale-aware slug generator

### ISSUE THREAD

**Issue by dinamic** [symfony-cmf/blog-bundle#13]
The current slug generator is a bit limited in terms of handling different languages:
- https://github.com/symfony-cmf/BlogBundle/blob/master/Util/PostUtils.php

I tried to use it with my local language:

```
[ErrorException]
Notice: iconv(): Detected an illegal character in input string in ...\vendor\symfony-cmf\blog-bundle\Symfony\Cmf\Bundle\BlogBundle\Util\PostUtils.php line 20
```

Is there some library that can be integrated to provide locale-aware slug generator?

In all cases the developer knows which locale is being used for the document, so generic ones, I think, are outside the scope of the question.

**Comment by dinamic** [comment]
@dantleech is now a good time to have this implemented? i haven't been in the loop for a few years.

**Comment by dinamic** [comment]
Shortly after I wrote this comment I noticed the bundle is abandoned. Frankly, I don't think I'll have the time to address incoming issues and develop the bundle further.

I guess we can close this issue down. It does not seem relevant any longer. Also, time could be spend on other areas - maybe refactoring to make the Symfony CMF work with Symfony 4.x, if that's a thing.

**Comment by dbu** [comment]
agreed. symfony 4 and flex support is very much a thing, yes. i guess the best issue to see flex support tracking is https://github.com/symfony-cmf/symfony-cmf/issues/250 , although looking at it i think its a bit outdated. lets discuss in https://github.com/symfony-cmf/symfony-cmf/issues/250 ;-)
